### ISSUE TITLE
Bug: Citizens Hologram, equip, Chat not found.

### ISSUE THREAD

**Issue by SmellyOG** [Samsuik/Sakura#1]
Citizens break with sakura spigot https://prnt.sc/ujrhaI_Ej2cR
Citizens whitout sakura https://prnt.sc/Ug2Th8IfpaHr
Chat disabled with sakura spigot https://prnt.sc/4MnbkH7a2q0f

**Comment by Samsuik** [comment]
Citizens holograms should be fixed with commit 8e60224ca3214e50b630c22be46b9a075b5a75ca 

The chat issue is likely unrelated to Sakura. We do not make any changes that would affect chat signing. It could be plugins, the proxy, client or even upstream _but that is quite far fetched_.
