### ISSUE TITLE
Left/right shooting

### ISSUE THREAD

**Issue by Techirion** [Samsuik/Sakura#18]
Jugging by feedback from our players left/right shooting is uncapped with this .jar, maybe it would make sense to add option to nerf it?

I'm not much of an expert on cannons but it appears blossom had similar patch? And I remember old 1.8 .jar's had option to disable this...

Patch I'm referring to... https://github.com/Samsuik/Blossom/commit/4cd56a9eb0f176b7e168d7ee3f936dbd4c72f15e

**Comment by Samsuik** [comment]
I added a patch to add limits to adjusting and left shooting. The adjusting limits are to restrict triangle left shooting that adjust on the walls, and the left shooting limits are for traditional left shooters.
