### ISSUE TITLE
Water logged defenses

### ISSUE THREAD

**Issue by CuprizeDev** [Samsuik/Sakura#19]
The current 'destroy-waterlogged-blocks' option destroys blocks that are not water logged and have water covering them. This makes cannons blow up. Make it so only blocks that ARE waterlogged only get damaged.

**Comment by Samsuik** [comment]
This should now be fixed. Explosions when the `destroy-waterlogged-blocks` option was enabled would destroy all fluids regardless of if they were inside a waterlogged block.
