### ISSUE TITLE
Citizens bug

### ISSUE THREAD

**Issue by SmellyOG** [Samsuik/Sakura#2]
With sakura spigot https://prnt.sc/6DQ772RMfVPI
without u spigot https://prnt.sc/fbIGrlPmoAqG

**Comment by SmellyOG** [comment]
look irongolem

**Comment by Samsuik** [comment]
I was not able to reproduce this locally with citizens but this should be fixed in the latest release with 8fe647d02b07b367a66a3e4b37a5288500cb2322. I will leave this issue open because I am not sure my changes will fix the issue.

**Comment by SmellyOG** [comment]
close the insuee, its citizens
