### ISSUE TITLE
[Question] Transfer from Purpur and compatibility queries 

### ISSUE THREAD

**Issue by joehosten** [Samsuik/Sakura#24]
Hi there,

I couldn't find a good way to contact the developer(s) of Sakura, so I'm resorting to an Issue Card.

I'm a developer for a Factions server running on Purpur 1.20.x and would like to know some details about Sakura. Most importantly, does Sakura have the same, or similar, features as Purpur's Pufferfish? Mainly:

- Entity related optimizations (async spawning, DAB, movement etc)

Will Sakura have any direct compatibility issues with Purpur compatible softwares. And if you know, does Sakura have any compatibility issues with [Iris](https://www.spigotmc.org/resources/iris-dimension-engine.84586/)

These answers will either make or break the dilemma we're facing.

**Comment by Samsuik** [comment]
This project is based on Paper, and does not contain any features or optimisations from Pufferfish and Purpur. Pretty much anything that works on Paper will work on Sakura as well.

**Comment by joehosten** [comment]
Okay thank you! I'll figure something out.
