### ISSUE TITLE
optimise-protected-regions

### ISSUE THREAD

**Issue by Hermelijn15** [Samsuik/Sakura#3]
I assume optimise protected regions only works in combination with plugins, protection blocks? atm turning it on prevents all explosions from breaking blocks

**Comment by Samsuik** [comment]
Ah, that is an issue. It is supposed to fire an explosion event before block searching with the block at the explosion location, and if a plugin removes that block or cancels the event it is a protected region and won't search for blocks to destroy.

**Comment by Samsuik** [comment]
Fixed with 4c72d655916e0bede47bc63c7508dc3983e7211c
