### ISSUE TITLE
Bug destroy chest/shulker

### ISSUE THREAD

**Issue by SmellyOG** [Samsuik/Sakura#6]
When you destroy a chest/shulker/double chest... it doesn't give you the items inside the chest

**Comment by Samsuik** [comment]
This is a plugin issue or the doTileDrops gamerule was changed. I am unable to reproduce this locally.

**Comment by SmellyOG** [comment]
I've tested it without any plugins
dotitledrops is ture

**Comment by SmellyOG** [comment]
can u check pls?

**Comment by SmellyOG** [comment]
mc.titanet.it factions server to test with me

**Comment by SmellyOG** [comment]
close inssue
