### ISSUE TITLE
Crash lasversion spigot 

### ISSUE THREAD

**Issue by SmellyOG** [Samsuik/Sakura#7]
https://api.mclo.gs/1/raw/pHJwWiR

**Comment by Hermelijn15** [comment]
looks like fawe is causing the crash

**Comment by SmellyOG** [comment]
If I use PaperSpigot, it doesn't happen.

**Comment by Hermelijn15** [comment]
I think some plugins try to use nms, or detect what server version you are using. Which is what causes the issue.

**Comment by SmellyOG** [comment]
How soon can you fix this?

**Comment by Samsuik** [comment]
Many of those plugins in that log are out of date and require updating to support 1.20.2.
