### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Hermelijn15** [Samsuik/Sakura#9]
I have some suggestions, but not all are needed and some can be handled by plugins as well. I will also try to help a bit (it will be slow)

configurable base attack speed (to emulate 1.8 combat if you want to)
disable sweep attack (again emulate 1.8)
change duration and availability of potions (for example you can buff or disable invis pots)
configurable golden/enchanted apples (cooldown and effect)
configurable enderpearl cooldown (vanilla places a white loading par over items on cooldown, maybe the duration for this can get changed, if possible it would be nice to make each usuable/consumable item have a configurable cooldown with corresponding animation)

let me know if you like the suggestions or if they are better suited for a plugin

**Comment by Samsuik** [comment]
All of those suggestions are better implemented as a plugin. I would prefer only implementing features that cannot be done as a plugin or relevant to an existing change for convenience.

**Comment by Hermelijn15** [comment]
makes sense
